version: 2
updates:
  - package-ecosystem: "github-actions"
    cooldown:
      default-days: 7
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "gradle"
    open-pull-requests-limit: 10
    cooldown:
      default-days: 7
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-name: "com.viaversion:viarewind-common"
      - dependency-name: "com.viaversion:viabackwards-common"
